"""empty message

Revision ID: bf18c54691ba
Revises: 
Create Date: 2022-03-25 17:00:59.835021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf18c54691ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suscription_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=48), nullable=False),
    sa.Column('regular', sa.Boolean(), nullable=False),
    sa.Column('days', sa.String(length=96), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('sessions_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sessions_type_id'], ['sessions_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=48), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('suscription_image', sa.String(length=256), nullable=False),
    sa.Column('suscription_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suscription_type_id'], ['suscription_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('available_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessions_type_id', sa.Integer(), nullable=False),
    sa.Column('suscription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sessions_type_id'], ['sessions_type.id'], ),
    sa.ForeignKeyConstraint(['suscription_id'], ['suscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=24), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('adress', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=128), nullable=True),
    sa.Column('conditions_terms', sa.Boolean(), nullable=False),
    sa.Column('marketing_comunication', sa.Boolean(), nullable=False),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('suscription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['suscription_id'], ['suscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('stripe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['suscription_id'], ['suscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sessions_id', sa.Integer(), nullable=False),
    sa.Column('is_coach', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sessions_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sessions')
    op.drop_table('payments')
    op.drop_table('user')
    op.drop_table('available_sessions')
    op.drop_table('suscription')
    op.drop_table('sessions')
    op.drop_table('suscription_type')
    op.drop_table('sessions_type')
    op.drop_table('role')
    # ### end Alembic commands ###
