"""empty message

Revision ID: c4121dc83f04
Revises: 2807edd385a2
Create Date: 2022-03-24 18:11:02.437962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4121dc83f04'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=48), nullable=False),
    sa.Column('regular', sa.Boolean(), nullable=False),
    sa.Column('days', sa.String(length=96), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=48), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suscription_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_coach', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('adress', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('conditions_terms', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('first_name', sa.String(length=24), nullable=False))
    op.add_column('user', sa.Column('info', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('marketing_comunication', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=16), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=24), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'marketing_comunication')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'info')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'conditions_terms')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'adress')
    op.drop_table('user_sessions')
    op.drop_table('suscription_type')
    op.drop_table('suscription')
    op.drop_table('sessions_type')
    op.drop_table('sessions')
    op.drop_table('roles')
    op.drop_table('payments')
    op.drop_table('available_sessions')
    # ### end Alembic commands ###
